# .github/workflows/ci.yml
name: Web App CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install linters
      run: |
        npm install -g htmlhint stylelint eslint

    - name: Run HTMLHint
      run: htmlhint index.html

    - name: Run Stylelint
      run: stylelint "**/*.css" || true

    - name: Run ESLint
      run: eslint script.js || true
